runtime: php55
api_version: 1
threadsafe: true

handlers:
# Serve php scripts.
# - url: /(.+\.php)$
#  script: \1
- url: /tasks/cron-weekly
  script: /tasks/cron-weekly.php
- url: /tasks/cron-daily
  script: /tasks/cron-daily.php