<?php
require $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
require $_SERVER['DOCUMENT_ROOT'] . '/functions.php';

use PHPMailer\PHPMailer\PHPMailer;

$mail = new PHPMailer();
$mail->SMTPDebug = 2;
/* //setup mailtrap
$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = 'e62458779718b2'; //paste one generated by Mailtrap
$mail->Password = 'aa625b7617c3db' ; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525; */

//setup gmail
$mail->isSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'frefeys@gmail.com'; 
$mail->Password = 'kB9YX5FMsFC873BKWte3' ; 
$mail->SMTPSecure = 'tls';
$mail->Port = 587;

//headers
$mail->setFrom('info@openbestuur.be', 'Mailman');
$mail->addReplyTo('info@openbestuur.be', 'Mailtrap');
$mail->addAddress('frefeys@gmail.com', 'Fred'); 
$mail->addCC('cc1@example.com', 'Elena');
$mail->addBCC('bcc1@example.com', 'Alex');

// mail
$mail->isHTML(true);
$mail->Subject = 'Test email from freddy';
$mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
    <p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
$mail->Body = $mailContent;

// $mail->msgHTML(file_get_contents('contents.html'), __DIR__);

if($mail->send()){
    echo 'Message has been sent';
}else{
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;

    // files must be in the same dir! $mail->addAttachment('path/to/invoice1.pdf', 'invoice1.pdf');
}

?>